# Generated by Django 4.0.6 on 2022-08-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xcelcomp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelfiles',
            name='duplicate_free',
            field=models.FileField(blank=True, null=True, upload_to='duplifree'),
        ),
        migrations.AddField(
            model_name='excelfiles',
            name='duplicates_file',
            field=models.FileField(blank=True, null=True, upload_to='duplicate'),
        ),
        migrations.AlterField(
            model_name='excelfiles',
            name='excel',
            field=models.FileField(blank=True, null=True, upload_to='excels'),
        ),
    ]
